name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Variables Naming Rules
      id: variables-naming-rules
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Variables Naming Rules
        setup-command: npm install
        command: npm test
        timeout: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        VARIABLES-NAMING-RULES_RESULTS: "${{steps.variables-naming-rules.outputs.result}}"
      with:
        runners: variables-naming-rules
